VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "R1CAB016"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public d_hra_cfc_eln  As String
Public u_cfc_eln_prp  As String
Public c_idt_trn_eln  As String
Public n_cee_etd      As String
Public e_sit_cfc_eln  As String

Public Sub Class_Initialize()

End Sub
